name: Publish to npm with Yarn

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install Yarn
        run: npm install -g yarn@3.3.1

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Run tests with Yarn
        run: yarn test

      - name: Publish to npm with Yarn
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
