name: Publish to npm with Yarn

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install Yarn
        run: npm install -g yarn@1.22.21

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Run tests with Yarn
        run: yarn test
